import {
  setRetypeError,
  getUser,
  loginUser,
  logoutUser,
  registerUser,
  getSpecies,
  getDetails,
  deleteSpecies,
  updateSpeciesGeometry,
  getReactions,
  setReactionMode,
  postSubmission,
  getCollections,
  postNewCollection,
  postCollectionSpecies,
  deleteCollectionSpecies,
  deleteCollection,
} from "./store";

const actions = {
  setRetypeError,
  getUser,
  loginUser,
  logoutUser,
  registerUser,
  getSpecies,
  getDetails,
  deleteSpecies,
  updateSpeciesGeometry,
  getReactions,
  setReactionMode,
  postSubmission,
  getCollections,
  postNewCollection,
  postCollectionSpecies,
  deleteCollectionSpecies,
  deleteCollection,
};

export default actions;
