import {
  setRetypeError,
  getUser,
  loginUser,
  logoutUser,
  registerUser,
  getSpecies,
  getSpeciesDetails,
  addNewSpecies,
  clearNewSpecies,
  postNewSpecies,
  deleteSpecies,
  updateSpeciesGeometry,
  postSubmission,
  getCollections,
  postNewCollection,
  postCollectionSpecies,
  deleteCollectionSpecies,
  deleteCollection,
} from "./store";

const actions = {
  setRetypeError,
  getUser,
  loginUser,
  logoutUser,
  registerUser,
  getSpecies,
  getSpeciesDetails,
  addNewSpecies,
  clearNewSpecies,
  postNewSpecies,
  deleteSpecies,
  updateSpeciesGeometry,
  postSubmission,
  getCollections,
  postNewCollection,
  postCollectionSpecies,
  deleteCollectionSpecies,
  deleteCollection,
};

export default actions;
